[profile.default]
src = "src"
out = "out"
libs = ["node_modules", "lib"]
remappings = [
    '@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/',
    '@openzeppelin/contracts-upgradeable/=node_modules/@openzeppelin/contracts-upgradeable/',
    'erc721a-upgradeable/=node_modules/erc721a-upgradeable/'
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
